@extends('dashboard::layouts.dash')

@section('page-content')
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-share"></i>Affiliate Program</h4>
            </div>
            <div class="panel-body">

                {!! BootForm::open(['method' => 'POST']) !!}
                <div class="row">
                    <div class="form-group">
                        <label class="col-md-12 control-label">End User License Agreement</label>
                        <div class="col-md-12">
                            <div style="border: 1px solid #e5e5e5; height: 300px; overflow: auto; padding: 10px;">


                                <p>IMPORTANT: THIS SOFTWARE END-USER LICENSE AGREEMENT ("EULA") IS A LEGAL AGREEMENT BETWEEN YOU (EITHER AN INDIVIDUAL OR, IF PURCHASED OR OTHERWISE ACQUIRED BY OR FOR AN ENTITY, AN ENTITY) AND The Mini Mailer. READ IT CAREFULLY BEFORE COMPLETING THE INSTALLATION PROCESS AND USING THE SOFTWARE. IT PROVIDES A LICENSE TO USE THE SOFTWARE AND CONTAINS TERMINATION AND WARRANTY INFORMATION AND LIABILITY DISCLAIMERS. BY INSTALLING AND USING THE SOFTWARE, YOU ARE CONFIRMING YOUR ACCEPTANCE OF THE SOFTWARE AND AGREEING TO BECOME BOUND BY THE TERMS OF THIS EULA. IF YOU DO NOT AGREE TO BE BOUND BY THESE TERMS, THEN DO NOT INSTALL THE SOFTWARE AND RETURN THE SOFTWARE TO YOUR PLACE OF PURCHASE FOR A FULL REFUND.
                                THIS EULA SHALL APPLY ONLY TO THE SOFTWARE SUPPLIED BY The Mini Mailer HEREWITH REGARDLESS OF WHETHER OTHER SOFTWARE IS REFERRED TO OR DESCRIBED HEREIN.
                                </p>

                                <i>1. Definitions</i><br><br>
                                (a) "The Mini Mailer” means TheMiniMailer.com
                                <br>(b) "You" means the individual or entity entering into this EULA.
                                <br>(c) "Licensed Server" means the one (1) server having the Internet Protocol Address that you have provided in your Pricing and Term Agreement, to which the licenses granted pursuant to this EULA shall apply. A Licensed Server may be a Virtual Private Server.
                                <br>(d) "Pricing and Term Agreement" means the Pricing and Term Agreement or other similar agreement executed, acknowledged or otherwise agreed to by you in connection with the license of the Software, which sets forth (among other things) the price and term of the license granted under this EULA.
                                <br>(e) “Software" means only The Mini Mailer software program(s) and third-party software programs, in each case, supplied by The Mini Mailer  herewith, and corresponding documentation, associated media, printed materials, and online or electronic documentation.
                                <br><br><i>2. Pricing and Term Agreement</i><br><br>
                                Your Pricing and Term Agreement is hereby incorporated by reference and made a part of this EULA. All terms and conditions set forth in your Pricing and Term Agreement shall apply to this EULA as if expressly set forth herein. For the avoidance of doubt, any reference to "this EULA" shall also mean to include a reference to your Pricing and Term Agreement.
                                <br><br> <i> 3. License Grants</i><br><br>
                                <br>The licenses granted in this Section 3 are subject to the terms and conditions set forth in this EULA:
                                <br>(a) You may install and use the Software only on the Licensed Server. You may not install or use the Software on any other server’s other than the Licensed Server.  In order to install and use the Software on server’s other than the Licensed Server, you will need to obtain a separate license for each additional server, including a separate license for each additional Virtual Private Server.
                                <br>(b) You may sub-license the right to use (but not the right to install) the Software to any and all third-party users of the Licensed Server ("Third Party Users"); provided, however, that such Third Party Users are eighteen (18) years or older. NOTWITHSTANDING THE FOREGOING, YOUR RIGHT TO SUB-LICENSE THE USE OF THE SOFTWARE TO A THIRD-PARTY USER IS conditioned upon you and each Third Party User separately agreeing as follows:
                                <br>(i) The Third-Party User's right to use the Software in connection with the Licensed Server is made pursuant and subject to the license granted to you under this EULA;
                                <br>(ii) The Third-Party User's use of the Software is subject to the warranty disclaimers set forth in Section 9 below;
                                <br>(iii) The Third-Party User may use the Software as long as this EULA is effective and valid. The Third-Party User's right to use the Software shall automatically expire without any notice upon the expiration or termination of this EULA for any reason whatsoever. The Mini Mailer   reserves the right in its sole and absolute discretion to terminate each Third-Party User's access to and use of the Software upon the expiration or termination of this EULA or in the event that you breach this EULA. Upon such expiration or termination of this EULA, access to and use of the Software by the Third-Party User in connection with the Licensed Server will not be available; and
                                <br>(iv) You and the Third-Party User agree to waive any and all claims (whether under law, equity or any other theory of liability) against The Mini Mailer and its authorized sub-licensors that may arise from the Third Party User's inability to use the Software upon the expiration or termination of this EULA for any reason whatsoever.
                                <br><br> The terms of this Section 3<br>
                                <br>(b) must be expressly incorporated into any agreement between you and any Third-Party User concerning the use of the Software.  Use of or access to the Software on a Licensed Server by Third Party Users who have not agreed to the terms of this Section 3(b) will exceed the scope of the license grant and is expressly prohibited.
                                Upon the request of The Mini Mailer from time to time, you shall provide The Mini Mailer copies of such agreements between you and the Third-Party Users. The Mini Mailer shall also have the right (but not the obligation) to notify the Third Party Users when this EULA will expire or be terminated, and that the Software will not be available to them thereafter under this EULA.
                                <br>(c) In the event the Software is distributed along with other The Mini Mailer software products as part of a suite of products (collectively, the "Package"), the license of the Package is licensed as a single product and none of the products in the Package, including the Software, may be separated for installation, or use other than on the Licensed Server.
                                <br>(d) You may make one copy of the Software in machine-readable form solely for backup purposes. You must reproduce on any such copy all copyright notices and any other proprietary legends on the original copy of the Software. You may not sell or transfer any copy of the Software made for backup purposes except in conjunction with a duly authorized sale or transfer.
                                <br>(e) You agree that The Mini Mailer may audit your use of the Software for compliance with these terms at any time, upon reasonable notice. In the event that such audit reveals any use of the Software by you other than in full compliance with the terms of this EULA, you shall reimburse The Mini Mailer for all reasonable expenses related to such audit in addition to any other liabilities you may incur as a result of such non-compliance. You agree that The Mini Mailer  may use technological means to monitor your use of the Software and you hereby consent to such technological means as may be necessary to monitor your use of the Software without notice by The Mini Mailer .
                                <br>(f) Your license rights under this EULA are non-exclusive. In addition, your license rights under this EULA are non-transferable unless otherwise agreed by The Mini Mailer.
                                <br>(g) Mandatory Product Activation and Authentication System. The license rights granted under this Agreement may be limited to the first fifteen (15) days after you first install the Software unless you supply information required to activate your licensed copy in the manner described during the setup sequence of the Software. You may need to activate the Software through the use of the Internet or telephone; toll charges may apply. The Software contains technological measures that working in conjunction with computer servers operated by The Mini Mailer are designed to prevent unlicensed or illegal use of the Software ("Authentication System"). Such Authentication System allows The Mini Mailer   to (among other things) monitor your use of the Software, ensure that the Software is only used for the Licensed Server and terminate use of the Software upon the expiration or termination of the licenses granted under this EULA (as the case may be). You agree that The Mini Mailer may use those measures to disable access to and the use of the Software by You or any Third-Party Users of your Licensed Server.  You agree not to thwart, interfere or block the operation of any aspect of the Authentication System. Product activation and use of the Software requires the exchange of information between the Licensed Server and The Mini Mailer .
                                <br><br> <i>4. License Restrictions</i><br><br>
                                (a) Other than as set forth in Section 3, you may not make or distribute copies of the Software, or electronically transfer the Software from one computer to another or over a network.
                                <br>(b) Except for bug fixes, patches and other modifications for the Software provided to you by The Mini Mailer, you may not alter, merge, modify, adapt or translate the Software (including the source code) in any manner whatsoever.
                                <br>(c) You may not decompile, reverse engineer, disassemble, or otherwise reduce the Software to any human-readable form, create derivative works based upon the Software or use the Software to develop any application having the same primary function as the Software.
                                <br>(d) You may not rent, lease, or sublicense the Software except as otherwise provided in Section 3.
                                <br>(e) You may receive the Software in more than one medium but you shall only install or use one medium. Regardless of the number of media you receive, you may use only the medium that is appropriate for the Licensed Server on which the Software is to be installed.
                                <br>(f) You may receive the Software in more than one platform but you shall only install or use one platform.
                                <br>(g) If you’re Pricing and Term Agreement provides for an Educational License, Non-Profit License, or Trial Version License, you may not use the Software for any commercial purposes. Availability of these licenses is at the sole discretion of The Mini Mailer and subject to change.
                                <br>The Mini Mailer reserves the right to deny Non-Profit, Educational Licenses, or Trial licenses to companies that promote, host, or are associated with websites that violate or are discriminatory.
                                <br>(h) If you’re Pricing and Term Agreement provides for a Trial Version License, you may only use the Software to review and evaluate the Software.
                                <br>(i) Notwithstanding anything to the contrary, you may not use, install or sub-license the Software in any manner that may be in violation of any applicable laws, regulations, presidential executive orders and agency rulings.  Without limiting the foregoing, you may not use, install or sub-license the Software, directly or indirectly, in or to any country or any person where such use, installation or sub-license would be prohibited by virtue of any applicable law, regulation, presidential executive order or agency ruling.
                                <br><br> <i> 5. Upgrades</i><br><br>
                                If this copy of the Software is an upgrade from an earlier version of the Software, it is provided to you on a license exchange basis. You agree by your installation and use of such copy of the Software to voluntarily terminate your earlier EULA and that you will not continue to use the earlier version of the Software or transfer it to another person or entity.
                                <br><br> <i> 6. Ownership of Intellectual Property</i><br><br>
                                The foregoing license gives you a limited license to use and install the Software. The Mini Mailer retains all right, title and interest, including all copyright, trade secrets, trademarks and intellectual property rights, in and to, the Software and all copies thereof. All rights not specifically granted in this EULA, including, without limitation, copyright, trade secrets, and trademarks, are reserved by The Mini Mailer.
                                <br><br> <i>7. Payments</i><br><br>
                                In consideration of the licenses granted to you pursuant to this EULA, you shall pay The Mini Mailer the amount(s) set forth in your Pricing and Term Agreement in accordance with the payment terms contained therein.
                                <br><br> <i> 8. Term and Termination</i><br><br>
                                (a) The term of the licenses granted to you under this EULA is set forth your Pricing and Term Agreement. This EULA shall automatically expire upon the expiration of such term.
                                <br>(b) In the event that you fail to comply with any of the terms or conditions of this EULA, The Mini Mailer may immediately terminate this EULA with or without notice.
                                <br>(c) Upon the expiration or termination of this EULA as set forth above, you must destroy all copies of the Software and delete the Software from the Licensed Server. All rights of The Mini Mailer under this EULA shall survive such expiration or termination.
                                <br>(d) You hereby acknowledge and agree that The Mini Mailer , through its Authentication System, may automatically terminate your ability and each Third Party User's ability to access or use the Software upon the expiration, termination or breach of this EULA or upon the expiration, termination or breach of your Pricing and Term Agreement.
                                <br><br> <i> 9. Limited Warranty and Disclaimer</i><br><br>
                                (a) The Mini Mailer warrants that, for a period of ninety (30) days from the date of delivery of the Software: (i) when used with a recommended hardware configuration and installed as advised by The Mini Mailer , the Software will perform in substantial conformance; and (ii) the physical media on which the Software is furnished will be free from defects in materials and workmanship under normal use.  The warranty in this Section 9(a) shall not apply if your Pricing and Term Agreement provides for an Educational License, Non-Profit License or Trial Version License or BETA License.
                                <br>(b) EXCEPT AS SET FORTH IN THE FOREGOING LIMITED WARRANTY, THE SOFTWARE LICENSED HEREUNDER IS PROVIDED "AS IS" AND The Mini Mailer   HEREBY DISCLAIMS ALL OTHER WARRANTIES AND REPRESENTATIONS, WHETHER EXPRESS, IMPLIED, OR OTHERWISE, INCLUDING THE WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. ALSO, THERE ARE NO WARRANTIES OF NON-INFRINGEMENT, TITLE OR QUIET ENJOYMENT. The Mini Mailer DOES NOT WARRANT THAT THE SOFTWARE IS ERROR-FREE OR WILL OPERATE WITHOUT INTERRUPTION. NO RIGHTS OR REMEDIES REFERRED TO IN ARTICLE 2A OF THE UCC WILL BE CONFERRED ON YOU UNLESS EXPRESSLY GRANTED HEREIN. THE SOFTWARE IS NOT DESIGNED, INTENDED OR LICENSED FOR USE IN HAZARDOUS ENVIRONMENTS REQUIRING FAIL-SAFE CONTROLS, INCLUDING WITHOUT LIMITATION, THE DESIGN, CONSTRUCTION, MAINTENANCE OR OPERATION OF NUCLEAR FACILITIES, AIRCRAFT NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, AND LIFE SUPPORT OR WEAPONS SYSTEMS. The Mini Mailer SPECIFICALLY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTY OF FITNESS FOR SUCH PURPOSES.
                                <br>(c) IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE SOFTWARE, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO NINETY (30) DAYS FROM THE DATE OF DELIVERY.
                                <br>(d) NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY The Mini Mailer, ITS DEALERS, SUB-LICENSORS, AGENTS OR EMPLOYEES SHALL CREATE A WARRANTY OR IN ANY WAY INCREASE THE SCOPE OF ANY WARRANTY PROVIDED HEREIN.
                                <br><br> <i> 10. Exclusive Remedy</i><br><br>
                                Your exclusive remedy under the preceding Section 10 is to seek a refund for the Software. Provided that any non-compliance with the above warranty is reported in writing to The Mini Mailer no more than ninety (30) days following delivery to you, The Mini Mailer  will use reasonable commercial efforts to supply you with a replacement copy of the Software that substantially conforms to the documentation, provide a replacement for defective media, or refund to you your purchase price for the Software, at its option. The Mini Mailer shall have no responsibility if the Software has been altered in any way, if the media has been damaged by misuse, accident, abuse, modification or misapplication, or if the failure arises out of use of the Software with other than a recommended hardware configuration. Any such misuse, accident, abuse, modification or misapplication of the Software will void the warranty above. THIS REMEDY IS THE SOLE AND EXCLUSIVE REMEDY AVAILABLE TO YOU FOR BREACH OF EXPRESS OR IMPLIED WARRANTIES WITH RESPECT TO THE SOFTWARE AND RELATED DOCUMENTATION.
                                <br><br> <i>11. Limitation of Liability</i><br><br>
                                (a) The Mini Mailer   SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, COVER OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR THE INABILITY TO USE EQUIPMENT OR ACCESS DATA, LOSS OF BUSINESS, LOSS OF PROFITS, BUSINESS INTERRUPTION OR THE LIKE), ARISING OUT OF THE USE OF, OR INABILITY TO USE, THE SOFTWARE AND BASED ON ANY THEORY OF LIABILITY INCLUDING BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE, EVEN IF The Mini Mailer   OR ITS REPRESENTATIVES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.
                                <br>(b) The Mini Mailer ‘S TOTAL LIABILITY TO YOU FOR ACTUAL DAMAGES FOR ANY CAUSE WHATSOEVER WILL BE LIMITED TO THE AMOUNT PAID BY YOU FOR THE SOFTWARE THAT CAUSED SUCH DAMAGE.
                                <br>(c) THE FOREGOING LIMITATIONS ON LIABILITY ARE INTENDED TO APPLY TO THE WARRANTIES AND DISCLAIMERS ABOVE AND ALL OTHER ASPECTS OF THIS EULA.
                                <br><br> <i>12. Indemnification</i><br><br>
                                In the event that you sub-license the right use the Software to any Third Party Users pursuant to Section 3, you agree to indemnify, defend and hold The Mini Mailer  and each of its shareholders, affiliates, officers, directors, employees, agents, successors, assigns, partners, sub-licensors, distributors and resellers (collectively, the "Indemnified Parties") harmless from any and all loss, liability, damage or deficiency (including interest, penalties, costs of preparation and investigation, and reasonable legal" fees) that the Indemnified Parties may suffer, sustain, incur or become subject to, arising out of or due to any claims raised by any Third Party User in connection with the use or inability to use the Software for any reason whatsoever, including, without limitation, if this EULA is terminated pursuant to Section 8.
                                <br><br> <i> 13. Basis of Bargain</i><br><br>
                                The Limited Warranty and Disclaimer, Exclusive Remedies, Limited Liability and Indemnification set forth above are fundamental elements of the basis of the agreement between The Mini Mailer and you. The Mini Mailer would not be able to provide the Software on an economic basis without such limitations. Such Limited Warranty and Disclaimer, Exclusive Remedies, Limited Liability and Indemnification inure to the benefit of The Mini Mailer.
                                <br>This EULA (including the Pricing and Term Agreement) contains the complete agreement between the parties with respect to the subject matter hereof, and supersedes all prior or contemporaneous agreements or understandings, whether oral or written. You agree that any varying or additional terms contained in any other written notification or document issued by you in relation to the Software licensed hereunder shall be of no effect. The failure or delay of The Mini Mailer to exercise any of its rights under this EULA or upon any breach of this EULA shall not be deemed a waiver of those rights or of the breach.
                                <br>If any provision of this EULA shall be held by a court of competent jurisdiction to be contrary to law that provision will be enforced to the maximum extent permissible and the remaining provisions of this EULA will remain in full force and effect.
                                <br>All notices or questions relating to this EULA shall be directed to: Support@TheMiniMailer.com The Mini Mailer and other trademarks contained in the Software are trademarks or registered trademarks of The Mini Mailer. You may not remove or alter any trademark, trade names, product names, logo, copyright or other proprietary notices, legends, symbols or labels in the Software. This EULA does not authorize you to use The Mini Mailer ’s or its sub-licensors' names or any of their respective trademarks.


                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        {!! BootForm::checkbox('accept', 'I have read and agree to the Affiliate User Agreement', 1) !!}
                    </div>
                    <div class="col-md-12">
                        {!! BootForm::button('Accept', ['class' => 'btn btn-primary col-md-offset-4 col-md-4', 'type' => 'submit']) !!}
                    </div>
                </div>
                {!! BootForm::close() !!}
            </div>
        </div>
    </div>
@endsection